
package org.miloss.fgsms.services.interfaces.dataaccessservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "AccessDeniedException", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:faults")
public class AccessDeniedException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private org.miloss.fgsms.services.interfaces.faults.AccessDeniedException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public AccessDeniedException(String message, org.miloss.fgsms.services.interfaces.faults.AccessDeniedException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public AccessDeniedException(String message, org.miloss.fgsms.services.interfaces.faults.AccessDeniedException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.miloss.fgsms.services.interfaces.faults.AccessDeniedException
     */
    public org.miloss.fgsms.services.interfaces.faults.AccessDeniedException getFaultInfo() {
        return faultInfo;
    }

}
