
package org.oasis_open.docs.wsn.brw_2;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.oasis_open.docs.wsn.b_2.DestroyPullPoint;
import org.oasis_open.docs.wsn.b_2.DestroyPullPointResponse;
import org.oasis_open.docs.wsn.b_2.GetMessages;
import org.oasis_open.docs.wsn.b_2.GetMessagesResponse;
import org.oasis_open.docs.wsn.b_2.Notify;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PullPoint", targetNamespace = "http://docs.oasis-open.org/wsn/brw-2")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.oasis_open.docs.wsn.b_2.ObjectFactory.class,
    org.oasis_open.docs.wsn.t_1.ObjectFactory.class,
    org.oasis_open.docs.wsrf.r_2.ObjectFactory.class,
    org.oasis_open.docs.wsn.br_2.ObjectFactory.class,
    org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class
})
public interface PullPoint {


    /**
     * 
     * @param getMessagesRequest
     * @return
     *     returns org.oasis_open.docs.wsn.b_2.GetMessagesResponse
     * @throws UnableToGetMessagesFault
     * @throws ResourceUnknownFault
     */
    @WebMethod(operationName = "GetMessages", action = "GetMessages")
    @WebResult(name = "GetMessagesResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "GetMessagesResponse")
    public GetMessagesResponse getMessages(
        @WebParam(name = "GetMessages", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "GetMessagesRequest")
        GetMessages getMessagesRequest)
        throws ResourceUnknownFault, UnableToGetMessagesFault
    ;

    /**
     * 
     * @param destroyPullPointRequest
     * @return
     *     returns org.oasis_open.docs.wsn.b_2.DestroyPullPointResponse
     * @throws UnableToDestroyPullPointFault
     * @throws ResourceUnknownFault
     */
    @WebMethod(operationName = "DestroyPullPoint", action = "DestroyPullPoint")
    @WebResult(name = "DestroyPullPointResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "DestroyPullPointResponse")
    public DestroyPullPointResponse destroyPullPoint(
        @WebParam(name = "DestroyPullPoint", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "DestroyPullPointRequest")
        DestroyPullPoint destroyPullPointRequest)
        throws ResourceUnknownFault, UnableToDestroyPullPointFault
    ;

    /**
     * 
     * @param notify
     */
    @WebMethod(operationName = "Notify", action = "Notify")
    @Oneway
    public void notify(
        @WebParam(name = "Notify", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "Notify")
        Notify notify);

}
