
package org.oasis_open.docs.wsn.brw_2;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PullPointService", targetNamespace = "http://docs.oasis-open.org/wsn/brw-2")
public class PullPointService
    extends Service
{

    private final static URL PULLPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.oasis_open.docs.wsn.brw_2.PullPointService.class.getName());

   
   
        static {
           ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) {
            PULLPOINTSERVICE_WSDL_LOCATION = cl.getResource("brw-2impl.wsdl");
        } else {
            PULLPOINTSERVICE_WSDL_LOCATION = PublisherRegistrationManagerService.class.getClassLoader().getResource("brw-2impl.wsdl");
        }
    }

    public PullPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PullPointService() {
        super(PULLPOINTSERVICE_WSDL_LOCATION, new QName("http://docs.oasis-open.org/wsn/brw-2", "PullPointService"));
    }

    /**
     * 
     * @return
     *     returns PullPoint
     */
    @WebEndpoint(name = "PullPointBindingPort")
    public PullPoint getPullPointBindingPort() {
        return super.getPort(new QName("http://docs.oasis-open.org/wsn/brw-2", "PullPointBindingPort"), PullPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PullPoint
     */
    @WebEndpoint(name = "PullPointBindingPort")
    public PullPoint getPullPointBindingPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://docs.oasis-open.org/wsn/brw-2", "PullPointBindingPort"), PullPoint.class, features);
    }

}
