
package org.miloss.fgsms.services.interfaces.policyconfiguration;

import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * PCS Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PolicyConfigurationService", 
        targetNamespace = "urn:org:miloss:fgsms:services:interfaces:policyConfiguration"
        //issues with jbossws,         wsdlLocation = "classpath:/PCS8.wsdl"
)
public class PolicyConfigurationService
    extends Service
{

    private static URL POLICYCONFIGURATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.miloss.fgsms.services.interfaces.policyconfiguration.PolicyConfigurationService.class.getName());

        static {
           ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) {
            POLICYCONFIGURATIONSERVICE_WSDL_LOCATION = cl.getResource("PCS8.wsdl");
        } else {
            
            POLICYCONFIGURATIONSERVICE_WSDL_LOCATION = PolicyConfigurationService.class.getClassLoader().getResource("PCS8.wsdl");
        }
        if (POLICYCONFIGURATIONSERVICE_WSDL_LOCATION==null) {
            try{
            POLICYCONFIGURATIONSERVICE_WSDL_LOCATION = PolicyConfigurationService.class.getClassLoader().getParent().getResource("PCS8.wsdl");
            }catch (Exception ex){
            }
        }
        if (POLICYCONFIGURATIONSERVICE_WSDL_LOCATION==null) {
            POLICYCONFIGURATIONSERVICE_WSDL_LOCATION = PolicyConfigurationService.class.getClassLoader().getResource("/META-INF/wsdl/PCS8.wsdl");
        }
        if (POLICYCONFIGURATIONSERVICE_WSDL_LOCATION==null) {
            POLICYCONFIGURATIONSERVICE_WSDL_LOCATION = PolicyConfigurationService.class.getClassLoader().getResource("META-INF/wsdl/PCS8.wsdl");
        }
    }

    public PolicyConfigurationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyConfigurationService() {
        super(POLICYCONFIGURATIONSERVICE_WSDL_LOCATION, new QName("urn:org:miloss:fgsms:services:interfaces:policyConfiguration", "PolicyConfigurationService"));
    }

    /**
     * PCS Port
     * 
     * @return
     *     returns PCS
     */
    @WebEndpoint(name = "PCSPort")
    public PCS getPCSPort() {
        return super.getPort(new QName("urn:org:miloss:fgsms:services:interfaces:policyConfiguration", "PCSPort"), PCS.class);
    }

    /**
     * 
     * @return
     *     returns OpStatusService
     */
    @WebEndpoint(name = "opStatusServiceBinding")
    public OpStatusService getOpStatusServiceBinding() {
        return super.getPort(new QName("urn:org:miloss:fgsms:services:interfaces:policyConfiguration", "opStatusServiceBinding"), OpStatusService.class);
    }

}
