/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular
 * file, then You may include the notice in a location (such as a LICENSE
 * file in a relevant directory) where a recipient would be likely to look
 * for such a notice.

 * 
 */
 
/*  ---------------------------------------------------------------------------
 *  US Government, Department of the Army
 *  Army Materiel Command
 *  Research Development Engineering Command
 *  Communications Electronics Research Development and Engineering Center
 *  ---------------------------------------------------------------------------
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace org.miloss.FGSMS.services.interfaces.discovery
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:org:miloss:FGSMS:services:interfaces:discovery")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:org:miloss:FGSMS:services:interfaces:discovery", IsNullable = false)]
    public partial class AcsLocationRequest
    {

        private string replyAddressField;

        private int replyPortField;

        private string requestorsHostnameField;

        /// <remarks/>
        public string replyAddress
        {
            get
            {
                return this.replyAddressField;
            }
            set
            {
                this.replyAddressField = value;
            }
        }

        /// <remarks/>
        public int replyPort
        {
            get
            {
                return this.replyPortField;
            }
            set
            {
                this.replyPortField = value;
            }
        }

        /// <remarks/>
        public string requestorsHostname
        {
            get
            {
                return this.requestorsHostnameField;
            }
            set
            {
                this.requestorsHostnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:org:miloss:FGSMS:services:interfaces:discovery")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:org:miloss:FGSMS:services:interfaces:discovery", IsNullable = false)]
    public partial class AcsLocationResponse
    {

        private string acsServiceUrlField;

        /// <remarks/>
        public string AcsServiceUrl
        {
            get
            {
                return this.acsServiceUrlField;
            }
            set
            {
                this.acsServiceUrlField = value;
            }
        }
    }
}