
package org.miloss.fgsms.services.interfaces.reportingservice;

import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * Reporting Service 
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ReportingService", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService"
        //wsdlLocation = "classpath:/RSv6.wsdl"
)
public class ReportingService_Service
    extends Service
{

    private static URL REPORTINGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.miloss.fgsms.services.interfaces.reportingservice.ReportingService_Service.class.getName());

    
        static {
           ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) {
            REPORTINGSERVICE_WSDL_LOCATION = cl.getResource("RSv6.wsdl");
        } else {
            REPORTINGSERVICE_WSDL_LOCATION = ReportingService_Service.class.getClassLoader().getResource("RSv6.wsdl");
        }
         if (REPORTINGSERVICE_WSDL_LOCATION==null) {
            try{
            REPORTINGSERVICE_WSDL_LOCATION = ReportingService_Service.class.getClassLoader().getParent().getResource("RSv6.wsdl");
            }catch (Exception ex){
            }
        }
        if (REPORTINGSERVICE_WSDL_LOCATION==null) {
            REPORTINGSERVICE_WSDL_LOCATION = ReportingService_Service.class.getClassLoader().getResource("/META-INF/wsdl/RSv6.wsdl");
        }
        if (REPORTINGSERVICE_WSDL_LOCATION==null) {
            REPORTINGSERVICE_WSDL_LOCATION = ReportingService_Service.class.getClassLoader().getResource("META-INF/wsdl/RSv6.wsdl");
        }
    }
    
    public ReportingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReportingService_Service() {
        super(REPORTINGSERVICE_WSDL_LOCATION, new QName("urn:org:miloss:fgsms:services:interfaces:reportingService", "ReportingService"));
    }

    /**
     * Reporting Service Port
     * 
     * @return
     *     returns ReportingService
     */
    @WebEndpoint(name = "reportingServicePort")
    public ReportingService getReportingServicePort() {
        return super.getPort(new QName("urn:org:miloss:fgsms:services:interfaces:reportingService", "reportingServicePort"), ReportingService.class);
    }

    /**
     * 
     * @return
     *     returns OpStatusService
     */
    @WebEndpoint(name = "opStatusServiceBinding")
    public OpStatusService getOpStatusServiceBinding() {
        return super.getPort(new QName("urn:org:miloss:fgsms:services:interfaces:reportingService", "opStatusServiceBinding"), OpStatusService.class);
    }

}
