
package org.miloss.fgsms.services.interfaces.reportingservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Reporting Service Port Type
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "reportingService", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService")
public interface ReportingService {


    /**
     * Creates an HTML report with charts for the selected services, time range, and report types in a zip file.
     * 
     * @param request
     * @return
     *     returns org.miloss.fgsms.services.interfaces.reportingservice.ExportDataToHTMLResponseMsg
     * @throws ServiceUnavailableException
     * @throws AccessDeniedException
     */
    @WebMethod(operationName = "ExportDataToHTML", action = "urn:org:miloss:fgsms:services:interfaces:reportingService/reportingService/ExportDataToHTML")
    @WebResult(name = "ExportDataToHTMLResult", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService")
    @RequestWrapper(localName = "ExportDataToHTML", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService", className = "org.miloss.fgsms.services.interfaces.reportingservice.ExportDataToHTML")
    @ResponseWrapper(localName = "ExportDataToHTMLResponse", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService", className = "org.miloss.fgsms.services.interfaces.reportingservice.ExportDataToHTMLResponse")
    public ExportDataToHTMLResponseMsg exportDataToHTML(
        @WebParam(name = "request", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService")
        ExportDataRequestMsg request)
        throws AccessDeniedException, ServiceUnavailableException
    ;

    /**
     * 
     * 		Exports transactions logs for a given set of services, requires audit level permissions or higher for each service requested service
     * 		
     * 
     * @param request
     * @return
     *     returns org.miloss.fgsms.services.interfaces.reportingservice.ExportDataToCSVResponseMsg
     * @throws ServiceUnavailableException
     * @throws AccessDeniedException
     */
    @WebMethod(operationName = "ExportDataToCSV", action = "urn:org:miloss:fgsms:services:interfaces:reportingService/reportingService/ExportDataToCSV")
    @WebResult(name = "ExportDataToCSVResult", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService")
    @RequestWrapper(localName = "ExportDataToCSV", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService", className = "org.miloss.fgsms.services.interfaces.reportingservice.ExportDataToCSV")
    @ResponseWrapper(localName = "ExportDataToCSVResponse", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService", className = "org.miloss.fgsms.services.interfaces.reportingservice.ExportDataToCSVResponse")
    public ExportDataToCSVResponseMsg exportDataToCSV(
        @WebParam(name = "request", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:reportingService")
        ExportCSVDataRequestMsg request)
        throws AccessDeniedException, ServiceUnavailableException
    ;

}
