
package org.miloss.fgsms.services.interfaces.status;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.oasis_open.docs.wsn.client.CreatePullPointService;


/**
 * Status Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "StatusServiceService", targetNamespace = "urn:org:miloss:fgsms:services:interfaces:status"
        //wsdlLocation = "classpath:/Statusv6.wsdl"
        )
public class StatusServiceService
    extends Service
{

    private static URL STATUSSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.miloss.fgsms.services.interfaces.status.StatusServiceService.class.getName());

      static {
           ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) {
            STATUSSERVICESERVICE_WSDL_LOCATION = cl.getResource("Statusv6.wsdl");
        } else {
            STATUSSERVICESERVICE_WSDL_LOCATION = StatusServiceService.class.getClassLoader().getResource("Statusv6.wsdl");
        }
        
        if (STATUSSERVICESERVICE_WSDL_LOCATION==null) {
            try{
            STATUSSERVICESERVICE_WSDL_LOCATION = StatusServiceService.class.getClassLoader().getParent().getResource("Statusv6.wsdl");
            }catch (Exception ex){
            }
        }
        if (STATUSSERVICESERVICE_WSDL_LOCATION==null) {
            STATUSSERVICESERVICE_WSDL_LOCATION = StatusServiceService.class.getClassLoader().getResource("/META-INF/wsdl/Statusv6.wsdl");
        }
        if (STATUSSERVICESERVICE_WSDL_LOCATION==null) {
            STATUSSERVICESERVICE_WSDL_LOCATION = StatusServiceService.class.getClassLoader().getResource("META-INF/wsdl/Statusv6.wsdl");
        }
    }
    

    public StatusServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatusServiceService() {
        super(STATUSSERVICESERVICE_WSDL_LOCATION, new QName("urn:org:miloss:fgsms:services:interfaces:status", "StatusServiceService"));
    }

    /**
     * Status Port
     * 
     * @return
     *     returns StatusService
     */
    @WebEndpoint(name = "statusServicePort")
    public StatusService getStatusServicePort() {
        return super.getPort(new QName("urn:org:miloss:fgsms:services:interfaces:status", "statusServicePort"), StatusService.class);
    }

    /**
     * 
     * @return
     *     returns OpStatusService
     */
    @WebEndpoint(name = "opStatusServiceBinding")
    public OpStatusService getOpStatusServiceBinding() {
        return super.getPort(new QName("urn:org:miloss:fgsms:services:interfaces:status", "opStatusServiceBinding"), OpStatusService.class);
    }

}
