
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Service1", targetNamespace = "http://tempuri.org/",
        wsdlLocation = "classpath:/Service1.wsdl"
	)
public class Service1
    extends Service
{

    private final static URL SERVICE1_WSDL_LOCATION;
    
    private final static QName SERVICE1_QNAME = new QName("http://tempuri.org/", "Service1");

    static {
           ClassLoader cl = Thread.currentThread().getContextClassLoader();
        if (cl != null) {
            SERVICE1_WSDL_LOCATION = cl.getResource("Service1.wsdl");
        } else {
            SERVICE1_WSDL_LOCATION = Service1.class.getClassLoader().getResource("Service1.wsdl");
        }
    }
    public Service1() {
        super(SERVICE1_WSDL_LOCATION, SERVICE1_QNAME);
    }

    public Service1(WebServiceFeature... features) {
        super(SERVICE1_WSDL_LOCATION, SERVICE1_QNAME, features);
    }

    public Service1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE1_QNAME);
    }


    public Service1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }


    /**
     * 
     * @return
     *     returns IService1
     */
    @WebEndpoint(name = "BasicHttpBinding_IService1")
    public IService1 getBasicHttpBindingIService1() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IService1"), IService1.class);
    }


}
