/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular
 * file, then You may include the notice in a location (such as a LICENSE
 * file in a relevant directory) where a recipient would be likely to look
 * for such a notice.

 * 
 */
 
/*  ---------------------------------------------------------------------------
 *  U.S. Government, Department of the Army
 *  Army Materiel Command
 *  Research Development Engineering Command
 *  Communications Electronics Research Development and Engineering Center
 *  ---------------------------------------------------------------------------
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 12:37:46 PM EDT 
//


package org.miloss.fgsms.auxsrv.status;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import java.util.Calendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.miloss.fgsms.auxstatus package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Volatile_QNAME = new QName("", "volatile");
    private final static QName _Stateful_QNAME = new QName("", "stateful");
    private final static QName _SchedulerInstanceId_QNAME = new QName("", "scheduler-instance-id");
    private final static QName _JobsExecuted_QNAME = new QName("", "jobs-executed");
    private final static QName _Durable_QNAME = new QName("", "durable");
    private final static QName _Runningsince_QNAME = new QName("", "runningsince");
    private final static QName _SchedulerName_QNAME = new QName("", "scheduler-name");
    private final static QName _Version_QNAME = new QName("", "version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.miloss.fgsms.auxstatus
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupNames }
     * 
     */
    public GroupNames createGroupNames() {
        return new GroupNames();
    }

    /**
     * Create an instance of {@link QuartzStatus }
     * 
     */
    public QuartzStatus createQuartzStatus() {
        return new QuartzStatus();
    }

    /**
     * Create an instance of {@link Trigger }
     * 
     */
    public Trigger createTrigger() {
        return new Trigger();
    }

    /**
     * Create an instance of {@link Job }
     * 
     */
    public Job createJob() {
        return new Job();
    }

    /**
     * Create an instance of {@link Jobs }
     * 
     */
    public Jobs createJobs() {
        return new Jobs();
    }

    /**
     * Create an instance of {@link TriggerGroup }
     * 
     */
    public TriggerGroup createTriggerGroup() {
        return new TriggerGroup();
    }

    /**
     * Create an instance of {@link Triggers }
     * 
     */
    public Triggers createTriggers() {
        return new Triggers();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volatile")
    public JAXBElement<Boolean> createVolatile(Boolean value) {
        return new JAXBElement<Boolean>(_Volatile_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "stateful")
    public JAXBElement<Boolean> createStateful(Boolean value) {
        return new JAXBElement<Boolean>(_Stateful_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scheduler-instance-id")
    public JAXBElement<String> createSchedulerInstanceId(String value) {
        return new JAXBElement<String>(_SchedulerInstanceId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jobs-executed")
    public JAXBElement<Long> createJobsExecuted(Long value) {
        return new JAXBElement<Long>(_JobsExecuted_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "durable")
    public JAXBElement<Boolean> createDurable(Boolean value) {
        return new JAXBElement<Boolean>(_Durable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Calendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "runningsince")
    public JAXBElement<Calendar> createRunningsince(Calendar value) {
        return new JAXBElement<Calendar>(_Runningsince_QNAME, Calendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "scheduler-name")
    public JAXBElement<String> createSchedulerName(String value) {
        return new JAXBElement<String>(_SchedulerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

}
