/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular
 * file, then You may include the notice in a location (such as a LICENSE
 * file in a relevant directory) where a recipient would be likely to look
 * for such a notice.

 * 
 */
 
/*  ---------------------------------------------------------------------------
 *  U.S. Government, Department of the Army
 *  Army Materiel Command
 *  Research Development Engineering Command
 *  Communications Electronics Research Development and Engineering Center
 *  ---------------------------------------------------------------------------
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.08.30 at 12:37:46 PM EDT 
//


package org.miloss.fgsms.auxsrv.status;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Calendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}scheduler-name"/>
 *         &lt;element ref="{}scheduler-instance-id"/>
 *         &lt;element ref="{}version"/>
 *         &lt;element ref="{}jobs-executed"/>
 *         &lt;element ref="{}runningsince"/>
 *         &lt;element ref="{}group-names"/>
 *         &lt;element ref="{}jobs"/>
 *         &lt;element ref="{}triggers"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "schedulerName",
    "schedulerInstanceId",
    "version",
    "jobsExecuted",
    "runningsince",
    "groupNames",
    "jobs",
    "triggers"
})
@XmlRootElement(name = "quartz-status")
public class QuartzStatus {

    @XmlElement(name = "scheduler-name", required = true)
    protected String schedulerName;
    @XmlElement(name = "scheduler-instance-id", required = true)
    protected String schedulerInstanceId;
    @XmlElement(required = true)
    protected String version;
    @XmlElement(name = "jobs-executed")
    protected long jobsExecuted;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected Calendar runningsince;
    @XmlElement(name = "group-names", required = true)
    protected GroupNames groupNames;
    @XmlElement(required = true)
    protected Jobs jobs;
    @XmlElement(required = true)
    protected Triggers triggers;

    /**
     * Gets the value of the schedulerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerName() {
        return schedulerName;
    }

    /**
     * Sets the value of the schedulerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerName(String value) {
        this.schedulerName = value;
    }

    /**
     * Gets the value of the schedulerInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchedulerInstanceId() {
        return schedulerInstanceId;
    }

    /**
     * Sets the value of the schedulerInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchedulerInstanceId(String value) {
        this.schedulerInstanceId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the jobsExecuted property.
     * 
     */
    public long getJobsExecuted() {
        return jobsExecuted;
    }

    /**
     * Sets the value of the jobsExecuted property.
     * 
     */
    public void setJobsExecuted(long value) {
        this.jobsExecuted = value;
    }

    /**
     * Gets the value of the runningsince property.
     * 
     * @return
     *     possible object is
     *     {@link Calendar }
     *     
     */
    public Calendar getRunningsince() {
        return runningsince;
    }

    /**
     * Sets the value of the runningsince property.
     * 
     * @param value
     *     allowed object is
     *     {@link Calendar }
     *     
     */
    public void setRunningsince(Calendar value) {
        this.runningsince = value;
    }

    /**
     * Gets the value of the groupNames property.
     * 
     * @return
     *     possible object is
     *     {@link GroupNames }
     *     
     */
    public GroupNames getGroupNames() {
        return groupNames;
    }

    /**
     * Sets the value of the groupNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupNames }
     *     
     */
    public void setGroupNames(GroupNames value) {
        this.groupNames = value;
    }

    /**
     * Gets the value of the jobs property.
     * 
     * @return
     *     possible object is
     *     {@link Jobs }
     *     
     */
    public Jobs getJobs() {
        return jobs;
    }

    /**
     * Sets the value of the jobs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Jobs }
     *     
     */
    public void setJobs(Jobs value) {
        this.jobs = value;
    }

    /**
     * Gets the value of the triggers property.
     * 
     * @return
     *     possible object is
     *     {@link Triggers }
     *     
     */
    public Triggers getTriggers() {
        return triggers;
    }

    /**
     * Sets the value of the triggers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Triggers }
     *     
     */
    public void setTriggers(Triggers value) {
        this.triggers = value;
    }

}
