<%@include file="../csrf.jsp" %>
<div class="well">
    <h1>Versions</h1>
</div>
<div class="row-fluid">
    <div class="span12">
        <p>At the bottom of this web site, as well as in each and every file JAR distributed with FGSMS is a version number file (located in META-INF/version.txt). These versions make it easier for the development team to identify build numbers, SVN commit numbers, as well as major version numbers when troubleshooting problems.
        </p>
        <p>Example: 6.2 333 452
        <ul>
            <li>6.X - this is the major version number</li>
            <li>333 - this is the Subversion source code revision number which is generated every time someone checks in code for FGSMS.</li>
            <li>425 - this is the build number which is generated by the automated build and testing system used for FGSMS. It's called Jenkins.</li>
        </ul>
        <p>6.X</p>

    </div><!--/span-->
</div><!--/row-->

