//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceTestBed.JbossESBProxyBasicHelloWorld {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice_proxy_basic/helloworld", ConfigurationName="JbossESBProxyBasicHelloWorld.HelloWorld")]
    public interface HelloWorld {
        
        // CODEGEN: Generating message contract since the operation sayHello is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloResponse1 sayHello(WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice_proxy_basic/helloworld")]
    public partial class sayHello : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string toWhomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string toWhom {
            get {
                return this.toWhomField;
            }
            set {
                this.toWhomField = value;
                this.RaisePropertyChanged("toWhom");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice_proxy_basic/helloworld")]
    public partial class sayHelloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice_proxy_basic/helloworld", Order=0)]
        public WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHello sayHello;
        
        public sayHelloRequest() {
        }
        
        public sayHelloRequest(WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHello sayHello) {
            this.sayHello = sayHello;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice_proxy_basic/helloworld", Order=0)]
        public WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloResponse sayHelloResponse;
        
        public sayHelloResponse1() {
        }
        
        public sayHelloResponse1(WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloResponse sayHelloResponse) {
            this.sayHelloResponse = sayHelloResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : WebServiceTestBed.JbossESBProxyBasicHelloWorld.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<WebServiceTestBed.JbossESBProxyBasicHelloWorld.HelloWorld>, WebServiceTestBed.JbossESBProxyBasicHelloWorld.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloResponse1 WebServiceTestBed.JbossESBProxyBasicHelloWorld.HelloWorld.sayHello(WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloRequest request) {
            return base.Channel.sayHello(request);
        }
        
        public WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloResponse sayHello(WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHello sayHello1) {
            WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloRequest inValue = new WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloRequest();
            inValue.sayHello = sayHello1;
            WebServiceTestBed.JbossESBProxyBasicHelloWorld.sayHelloResponse1 retVal = ((WebServiceTestBed.JbossESBProxyBasicHelloWorld.HelloWorld)(this)).sayHello(inValue);
            return retVal.sayHelloResponse;
        }
    }
}
