/**
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 * If it is not possible or desirable to put the notice in a particular
 * file, then You may include the notice in a location (such as a LICENSE
 * file in a relevant directory) where a recipient would be likely to look
 * for such a notice.

 * 
 */
 
/*  ---------------------------------------------------------------------------
 *  US Government, Department of the Army
 *  Army Materiel Command
 *  Research Development Engineering Command
 *  Communications Electronics Research Development and Engineering Center
 *  ---------------------------------------------------------------------------
 */
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 

namespace aspnet.client.towcf
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IFGSMSNetService", Namespace = "http://tempuri.org/")]
    public partial class FGSMSNetServiceImpl : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getDataOperationCompleted;

        /// <remarks/>
        public FGSMSNetServiceImpl()
        {
            this.Url = "http://localhost:12345/JUnitTestService";
        }

        /// <remarks/>
        public event getDataCompletedEventHandler getDataCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:mil:army:cerdec:cpi:build/IFGSMSNetService/getData", RequestNamespace = "urn:mil:army:cerdec:cpi:build", ResponseNamespace = "urn:mil:army:cerdec:cpi:build", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public SomeComplexReturnObject getData([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] SomeComplexRequestObject request)
        {
            object[] results = this.Invoke("getData", new object[] {
                    request});
            return ((SomeComplexReturnObject)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetData(SomeComplexRequestObject request, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getData", new object[] {
                    request}, callback, asyncState);
        }

        /// <remarks/>
        public SomeComplexReturnObject EndgetData(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((SomeComplexReturnObject)(results[0]));
        }

        /// <remarks/>
        public void getDataAsync(SomeComplexRequestObject request)
        {
            this.getDataAsync(request, null);
        }

        /// <remarks/>
        public void getDataAsync(SomeComplexRequestObject request, object userState)
        {
            if ((this.getDataOperationCompleted == null))
            {
                this.getDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDataOperationCompleted);
            }
            this.InvokeAsync("getData", new object[] {
                    request}, this.getDataOperationCompleted, userState);
        }

        private void OngetDataOperationCompleted(object arg)
        {
            if ((this.getDataCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDataCompleted(this, new getDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:mil:army:cerdec:cpi:build")]
    public partial class SomeComplexRequestObject
    {

        private string durationField;

        private int responsecodeField;

        private bool responsecodeFieldSpecified;

        private string stderrField;

        private string stdoutField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        public int responsecode
        {
            get
            {
                return this.responsecodeField;
            }
            set
            {
                this.responsecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responsecodeSpecified
        {
            get
            {
                return this.responsecodeFieldSpecified;
            }
            set
            {
                this.responsecodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string stderr
        {
            get
            {
                return this.stderrField;
            }
            set
            {
                this.stderrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string stdout
        {
            get
            {
                return this.stdoutField;
            }
            set
            {
                this.stdoutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:mil:army:cerdec:cpi:build")]
    public partial class SomeComplexReturnObject
    {

        private string durationField;

        private int responsecodeField;

        private bool responsecodeFieldSpecified;

        private string stderrField;

        private string stdoutField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "duration")]
        public string duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        /// <remarks/>
        public int responsecode
        {
            get
            {
                return this.responsecodeField;
            }
            set
            {
                this.responsecodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responsecodeSpecified
        {
            get
            {
                return this.responsecodeFieldSpecified;
            }
            set
            {
                this.responsecodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string stderr
        {
            get
            {
                return this.stderrField;
            }
            set
            {
                this.stderrField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string stdout
        {
            get
            {
                return this.stdoutField;
            }
            set
            {
                this.stdoutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getDataCompletedEventHandler(object sender, getDataCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public SomeComplexReturnObject Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((SomeComplexReturnObject)(this.results[0]));
            }
        }
    }
}